# Generated by Django 5.1.4 on 2025-07-13 20:24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('solde', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('frequence_paiement', models.CharField(choices=[('journalier', 'Journalier'), ('hebdomadaire', 'Hebdomadaire'), ('mensuel', 'Mensuel')], default='journalier', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FactureFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_facture', models.DateField(default=django.utils.timezone.now)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('non payée', 'Non payée'), ('payée', 'Payée')], default='non payée', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FactureFournisseurCloturee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cloture', models.DateTimeField(default=django.utils.timezone.now)),
                ('montant_total_factures', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_total_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('factures_json', models.JSONField(blank=True, null=True)),
                ('paiements_json', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('solde', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('quantite_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unite', models.CharField(max_length=20)),
                ('seuil_minimum', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Jour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('0', 'Lundi'), ('1', 'Mardi'), ('2', 'Mercredi'), ('3', 'Jeudi'), ('4', 'Vendredi'), ('5', 'Samedi'), ('6', 'Dimanche')], max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorie', models.CharField(choices=[('croissanterie', 'Croissanterie'), ('sale', 'Salé'), ('patisserie', 'Pâtisserie')], default='croissanterie', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClientAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': '🧾 Clients - Bases',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.client',),
        ),
        migrations.CreateModel(
            name='CompteClient',
            fields=[
            ],
            options={
                'verbose_name': 'Compte client',
                'verbose_name_plural': 'Comptes clients',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.client',),
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_livraison', models.DateField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_speciale', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('En préparation', 'En préparation'), ('Livrée', 'Livrée')], default='En attente', max_length=20)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='gestion.client')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': '🛒 Commandes - Bases',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.commande',),
        ),
        migrations.CreateModel(
            name='CommandeModele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.client')),
                ('jours', models.ManyToManyField(related_name='modeles', to='gestion.jour')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeModeleAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Commande modèle',
                'verbose_name_plural': '🛒 Commandes - Modèles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.commandemodele',),
        ),
        migrations.CreateModel(
            name='CommandeModeleProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('commande_modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.commandemodele')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.produit')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeModeleProduitAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Commande modèle produit',
                'verbose_name_plural': '🛒 Commandes Modèles - Produits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.commandemodeleproduit',),
        ),
        migrations.CreateModel(
            name='CommandeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande_produits', to='gestion.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.produit')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeProduitAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Commande produit',
                'verbose_name_plural': '🛒 Commandes - Produits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.commandeproduit',),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_facture', models.DateTimeField(default=django.utils.timezone.now)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='gestion.commande')),
            ],
        ),
        migrations.CreateModel(
            name='FactureAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': '🧾 Clients - Factures',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.facture',),
        ),
        migrations.CreateModel(
            name='FactureCloturee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produits_json', models.JSONField(blank=True, null=True)),
                ('paiements_json', models.JSONField(blank=True, null=True)),
                ('date_facture', models.DateTimeField(default=django.utils.timezone.now)),
                ('montant_total_commandes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_total_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_cloturees', to='gestion.client')),
            ],
        ),
        migrations.CreateModel(
            name='FactureClotureeAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Facture clôturée',
                'verbose_name_plural': '🧾 Clients - Cloturées',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.facturecloturee',),
        ),
        migrations.CreateModel(
            name='FactureFournisseurAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Facture fournisseur',
                'verbose_name_plural': '🏢 Fournisseurs - Factures',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.facturefournisseur',),
        ),
        migrations.CreateModel(
            name='FactureFournisseurClotureeAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Facture fournisseur clôturée',
                'verbose_name_plural': '🏢 Fournisseurs - Cloturées',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.facturefournisseurcloturee',),
        ),
        migrations.AddField(
            model_name='facturefournisseurcloturee',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_cloturees', to='gestion.fournisseur'),
        ),
        migrations.AddField(
            model_name='facturefournisseur',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='gestion.fournisseur'),
        ),
        migrations.CreateModel(
            name='CompteFournisseur',
            fields=[
            ],
            options={
                'verbose_name': 'Compte fournisseur',
                'verbose_name_plural': 'Comptes fournisseurs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.fournisseur',),
        ),
        migrations.CreateModel(
            name='FournisseurAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': '🏢 Fournisseurs - Bases',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.fournisseur',),
        ),
        migrations.CreateModel(
            name='IngredientAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Ingrédient',
                'verbose_name_plural': '🍳 Ingrédients',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.ingredient',),
        ),
        migrations.CreateModel(
            name='PaiementClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField(default=django.utils.timezone.now)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement'), ('cheque', 'Chèque'), ('carte', 'Carte Bancaire')], default='especes', max_length=50)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='gestion.client')),
            ],
        ),
        migrations.CreateModel(
            name='PaiementClientAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Paiement client',
                'verbose_name_plural': '🧾 Clients - Paiements',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.paiementclient',),
        ),
        migrations.CreateModel(
            name='PaiementFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField(default=django.utils.timezone.now)),
                ('mode_paiement', models.CharField(choices=[('virement', 'Virement'), ('espèces', 'Espèces'), ('chèque', 'Chèque')], max_length=20)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='gestion.facturefournisseur')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='gestion.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='PaiementFournisseurAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Paiement fournisseur',
                'verbose_name_plural': '🏢 Fournisseurs - Paiements',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.paiementfournisseur',),
        ),
        migrations.AddField(
            model_name='commandemodele',
            name='produits',
            field=models.ManyToManyField(through='gestion.CommandeModeleProduit', to='gestion.produit'),
        ),
        migrations.AddField(
            model_name='commande',
            name='produits',
            field=models.ManyToManyField(through='gestion.CommandeProduit', to='gestion.produit'),
        ),
        migrations.CreateModel(
            name='ProduitAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': '🍰 Produits - Bases',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.produit',),
        ),
        migrations.CreateModel(
            name='ProduitIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.ingredient')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.produit')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='ingredients',
            field=models.ManyToManyField(through='gestion.ProduitIngredient', to='gestion.ingredient'),
        ),
        migrations.CreateModel(
            name='CompteClientAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Compte client',
                'verbose_name_plural': '🧾 Clients - Comptes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.compteclient',),
        ),
        migrations.CreateModel(
            name='CompteFournisseurAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Compte fournisseur',
                'verbose_name_plural': '🏢 Fournisseurs - Comptes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.comptefournisseur',),
        ),
    ]
