# Generated by Django 5.1.4 on 2025-04-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitingredient',
            name='unite',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
