# Generated by Django 5.1.4 on 2025-07-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='livre_par_nous',
            field=models.BooleanField(default=True, help_text='Indique si ce client est livré par nos soins'),
        ),
        migrations.AddField(
            model_name='client',
            name='mode_livraison',
            field=models.CharField(choices=[('bac', 'Par bacs'), ('paquet', 'Par paquets')], default='bac', help_text='Méthode de livraison pour le chargement', max_length=10),
        ),
    ]
