# Generated by Django 5.1.4 on 2025-05-22 13:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_compteclient_produit_ingredients_alter_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureCloturee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_facture', models.DateTimeField(default=django.utils.timezone.now)),
                ('montant_total_commandes', models.FloatField()),
                ('montant_total_paye', models.FloatField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_cloturees', to='gestion.client')),
            ],
        ),
    ]
