# Generated by Django 5.1.4 on 2025-07-13 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_client_livre_par_nous_client_mode_livraison'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EtapeLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('groupe', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.client')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='gestion.planlivraison')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='PlanLivraisonPrincipal',
            fields=[
            ],
            options={
                'verbose_name': 'Plan de livraison',
                'verbose_name_plural': '🚚 Plan de livraison',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.planlivraison',),
        ),
    ]
