# Generated by Django 5.1.4 on 2025-04-14 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_produitingredient_unite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitingredient',
            name='unite',
        ),
    ]
