# Generated by Django 5.1.4 on 2025-05-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_add_facturefournisseurcloturee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': '🧾 Clients',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.client',),
        ),
        migrations.CreateModel(
            name='CommandeAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': '🛒 Commandes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.commande',),
        ),
        migrations.CreateModel(
            name='CommandeModeleAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Commande modèle',
                'verbose_name_plural': '🛒 Commandes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.commandemodele',),
        ),
        migrations.CreateModel(
            name='CommandeModeleProduitAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Commande modèle produit',
                'verbose_name_plural': '🛒 Commandes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.commandemodeleproduit',),
        ),
        migrations.CreateModel(
            name='CommandeProduitAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Commande produit',
                'verbose_name_plural': '🛒 Commandes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.commandeproduit',),
        ),
        migrations.CreateModel(
            name='CompteClientAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Compte client',
                'verbose_name_plural': '🧾 Clients',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.compteclient',),
        ),
        migrations.CreateModel(
            name='CompteFournisseurAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Compte fournisseur',
                'verbose_name_plural': '🏢 Fournisseurs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.comptefournisseur',),
        ),
        migrations.CreateModel(
            name='FactureAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': '🧾 Clients',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.facture',),
        ),
        migrations.CreateModel(
            name='FactureClotureeAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Facture clôturée',
                'verbose_name_plural': '🧾 Clients',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.facturecloturee',),
        ),
        migrations.CreateModel(
            name='FactureFournisseurAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Facture fournisseur',
                'verbose_name_plural': '🏢 Fournisseurs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.facturefournisseur',),
        ),
        migrations.CreateModel(
            name='FactureFournisseurClotureeAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Facture fournisseur clôturée',
                'verbose_name_plural': '🏢 Fournisseurs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.facturefournisseurcloturee',),
        ),
        migrations.CreateModel(
            name='FournisseurAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': '🏢 Fournisseurs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.fournisseur',),
        ),
        migrations.CreateModel(
            name='IngredientAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Ingrédient',
                'verbose_name_plural': '🍳 Ingrédients',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.ingredient',),
        ),
        migrations.CreateModel(
            name='PaiementClientAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Paiement client',
                'verbose_name_plural': '🧾 Clients',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.paiementclient',),
        ),
        migrations.CreateModel(
            name='PaiementFournisseurAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Paiement fournisseur',
                'verbose_name_plural': '🏢 Fournisseurs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.paiementfournisseur',),
        ),
        migrations.CreateModel(
            name='ProduitAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': '🍰 Produits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.produit',),
        ),
    ]
