# Generated by Django 5.1.4 on 2025-07-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_planlivraison_etapelivraison_planlivraisonprincipal'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitingredient',
            name='matricule_fiscale',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
