# Generated by Django 5.1.4 on 2025-05-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_clientadminproxy_commandeadminproxy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientadminproxy',
            options={'verbose_name': 'Client', 'verbose_name_plural': '🧾 Clients - Bases'},
        ),
        migrations.AlterModelOptions(
            name='commandeadminproxy',
            options={'verbose_name': 'Commande', 'verbose_name_plural': '🛒 Commandes - Basea'},
        ),
        migrations.AlterModelOptions(
            name='commandemodeleadminproxy',
            options={'verbose_name': 'Commande modèle', 'verbose_name_plural': '🛒 Commandes - Modèles'},
        ),
        migrations.AlterModelOptions(
            name='commandemodeleproduitadminproxy',
            options={'verbose_name': 'Commande modèle produit', 'verbose_name_plural': '🛒 Commandes Modèles - Produits'},
        ),
        migrations.AlterModelOptions(
            name='commandeproduitadminproxy',
            options={'verbose_name': 'Commande produit', 'verbose_name_plural': '🛒 Commandes - Produits'},
        ),
        migrations.AlterModelOptions(
            name='compteclientadminproxy',
            options={'verbose_name': 'Compte client', 'verbose_name_plural': '🧾 Clients - Comptes'},
        ),
        migrations.AlterModelOptions(
            name='comptefournisseuradminproxy',
            options={'verbose_name': 'Compte fournisseur', 'verbose_name_plural': '🏢 Fournisseurs - Comptes'},
        ),
        migrations.AlterModelOptions(
            name='factureadminproxy',
            options={'verbose_name': 'Facture', 'verbose_name_plural': '🧾 Clients - Factures'},
        ),
        migrations.AlterModelOptions(
            name='factureclotureeadminproxy',
            options={'verbose_name': 'Facture clôturée', 'verbose_name_plural': '🧾 Clients - Cloturées'},
        ),
        migrations.AlterModelOptions(
            name='facturefournisseuradminproxy',
            options={'verbose_name': 'Facture fournisseur', 'verbose_name_plural': '🏢 Fournisseurs - Factures'},
        ),
        migrations.AlterModelOptions(
            name='facturefournisseurclotureeadminproxy',
            options={'verbose_name': 'Facture fournisseur clôturée', 'verbose_name_plural': '🏢 Fournisseurs - Cloturées'},
        ),
        migrations.AlterModelOptions(
            name='fournisseuradminproxy',
            options={'verbose_name': 'Fournisseur', 'verbose_name_plural': '🏢 Fournisseurs - Bases'},
        ),
        migrations.AlterModelOptions(
            name='paiementclientadminproxy',
            options={'verbose_name': 'Paiement client', 'verbose_name_plural': '🧾 Clients - Paiements'},
        ),
        migrations.AlterModelOptions(
            name='paiementfournisseuradminproxy',
            options={'verbose_name': 'Paiement fournisseur', 'verbose_name_plural': '🏢 Fournisseurs - Paiements'},
        ),
        migrations.AlterModelOptions(
            name='produitadminproxy',
            options={'verbose_name': 'Produit', 'verbose_name_plural': '🍰 Produits - Bases'},
        ),
    ]
