# Generated by Django 5.1.4 on 2025-01-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_commandeproduit_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='produits',
            field=models.ManyToManyField(through='gestion.CommandeProduit', to='gestion.produit'),
        ),
        migrations.AlterField(
            model_name='commandeproduit',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
