# Generated by Django 5.1.4 on 2025-05-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_facturecloturee'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturecloturee',
            name='paiements_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturecloturee',
            name='produits_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
