# Generated by Django 5.1.4 on 2025-05-17 10:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_livraison',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='commande',
            name='is_speciale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='remarque',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CommandeModele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.client')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeModeleProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('commande_modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.commandemodele')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.produit')),
            ],
        ),
        migrations.AddField(
            model_name='commandemodele',
            name='produits',
            field=models.ManyToManyField(through='gestion.CommandeModeleProduit', to='gestion.produit'),
        ),
    ]
