# Generated by Django 5.1.4 on 2025-07-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_produitingredient_matricule_fiscale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitingredient',
            name='matricule_fiscale',
        ),
        migrations.AddField(
            model_name='client',
            name='matricule_fiscale',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
