# Generated by Django 5.1.4 on 2025-05-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_clientadminproxy_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandeadminproxy',
            options={'verbose_name': 'Commande', 'verbose_name_plural': '🛒 Commandes - Bases'},
        ),
    ]
