# Generated by Django 5.1.4 on 2025-07-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_produitingredient_matricule_fiscale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturecloturee',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
