# Generated by Django 5.1.4 on 2025-05-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_commandeadminproxy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeproduit',
            name='prix_unitaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
