# Generated by Django 5.1.4 on 2025-05-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_commande_date_livraison_commande_is_speciale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('0', 'Lundi'), ('1', 'Mardi'), ('2', 'Mercredi'), ('3', 'Jeudi'), ('4', 'Vendredi'), ('5', 'Samedi'), ('6', 'Dimanche')], max_length=1, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='commandemodele',
            name='jours',
            field=models.ManyToManyField(related_name='modeles', to='gestion.jour'),
        ),
    ]
