# Generated by Django 5.1.4 on 2025-07-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_facturecloturee_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalNumerotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(unique=True)),
                ('dernier_numero', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
