# Generated by Django 5.1.4 on 2025-05-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_jour_commandemodele_jours'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('croissanterie', 'Croissanterie'), ('sale', 'Salé'), ('patisserie', 'Pâtisserie')], default='croissanterie', max_length=20),
        ),
    ]
