# Generated by Django 5.1.4 on 2025-05-20 08:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_produit_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='frequence_paiement',
            field=models.CharField(choices=[('journalier', 'Journalier'), ('hebdomadaire', 'Hebdomadaire'), ('mensuel', 'Mensuel')], default='journalier', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='solde',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='PaiementClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('date_paiement', models.DateField(default=django.utils.timezone.now)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement'), ('cheque', 'Chèque'), ('carte', 'Carte Bancaire')], default='especes', max_length=50)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='gestion.client')),
            ],
        ),
    ]
