# Generated by Django 5.1.4 on 2025-05-20 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_client_frequence_paiement_client_solde_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteClient',
            fields=[
            ],
            options={
                'verbose_name': 'Compte client',
                'verbose_name_plural': 'Comptes clients',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.client',),
        ),
    ]
