services:
  - type: web
    name: dusty-sugar
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations --noinput
      python manage.py migrate --noinput
      echo "from django.contrib.auth import get_user_model; \
User = get_user_model(); \
User.objects.create_superuser('admin', 'admin@example.com', 'admin1234') \
if not User.objects.filter(username='admin').exists() else print('✅ Superuser already exists')" \
| python manage.py shell
      python manage.py collectstatic --noinput
    startCommand: gunicorn dusty_sugar.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: DJANGO_SECRET_KEY
        value: "ta_clé_secrète_ici"
      - key: DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: dustysugar.onrender.com,dustysugar.tn
      - key: DATABASE_URL
        value: "postgresql://dustysugar_db_user:EkvKujbk9eXwC2ezPBJi02Zcdg5bpBTR@dpg-cvu9agje5dus73chfak0-a/dustysugar_db"
