services:
  - type: web
    name: dusty-sugar
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate       # ⬅️ migration forcée ici
      python manage.py collectstatic --noinput
    startCommand: gunicorn dusty_sugar.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: DJANGO_SECRET_KEY
        value: "ta_clé_secrète"
      - key: DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "dustysugar.onrender.com"
      - key: DATABASE_URL
        value: "ta_base_postgres_sur_render"
