# Generated by Django 5.1.4 on 2025-01-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_commande_produits_commandeproduit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandeproduit',
            name='quantite',
            field=models.IntegerField(),
        ),
    ]
