# Generated by Django 5.1.4 on 2025-01-13 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField(default=0)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('En préparation', 'En préparation'), ('Livrée', 'Livrée')], default='En attente', max_length=20)),
                ('produits', models.ManyToManyField(to='gestion.produit')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.ingredient')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.produit')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='ingredients',
            field=models.ManyToManyField(through='gestion.ProduitIngredient', to='gestion.ingredient'),
        ),
    ]
